version: "3.9"
services:
  app:
    build: ./app
    command: uwsgi --socket :8001 --module app.wsgi

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
      - app