version: "3.9"
services:
  app:
    build: ./app
    command: uwsgi --socket :8001 --module ####.wsgi

  nginx:
    image: nginx:1.21.0
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - app

  postgres:
      image: postgres:13.3-buster
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"